# Generated by Django 4.2 on 2023-05-10 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0005_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=6)),
                (
                    "maintenanceDate",
                    models.DateField(
                        default=datetime.datetime(2023, 5, 10, 8, 57, 50, 320204)
                    ),
                ),
                (
                    "mach",
                    models.CharField(
                        choices=[
                            ("PC", "PC - Run windows"),
                            ("Mac", "Mac - Run MacOS"),
                            (
                                "Serveur",
                                "Serveur - Simple Server to deploy virtual machines",
                            ),
                            ("Switch", "Switch - To maintains and connect servers"),
                        ],
                        default="PC",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=6)),
                (
                    "maintenanceDate",
                    models.DateField(
                        default=datetime.datetime(2023, 5, 10, 8, 57, 50, 319883)
                    ),
                ),
                (
                    "mach",
                    models.CharField(
                        choices=[
                            ("PC", "PC - Run windows"),
                            ("Mac", "Mac - Run MacOS"),
                            (
                                "Serveur",
                                "Serveur - Simple Server to deploy virtual machines",
                            ),
                            ("Switch", "Switch - To maintains and connect servers"),
                        ],
                        default="PC",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 10, 8, 57, 50, 318883)
            ),
        ),
    ]
