# Generated by Django 4.2 on 2023-05-11 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0006_infrastructure_personne_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Infrastructure",
        ),
        migrations.DeleteModel(
            name="Personne",
        ),
        migrations.RenameField(
            model_name="machine",
            old_name="mach",
            new_name="Type",
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 11, 9, 5, 54, 500324)
            ),
        ),
    ]
