# Generated by Django 4.2 on 2023-05-26 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0013_alter_machine_maintenancedate_infrastructure"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infrastructure",
            old_name="nom_infra",
            new_name="nom",
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 26, 7, 33, 15, 58845)
            ),
        ),
    ]
