# Generated by Django 4.2 on 2023-06-08 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0014_rename_nom_infra_infrastructure_nom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commutateur",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=6)),
                (
                    "maintenanceDate",
                    models.DateField(
                        default=datetime.datetime(2023, 6, 8, 18, 25, 52, 725312)
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("PC", "PC - Run windows"),
                            ("Mac", "Mac - Run MacOS"),
                            (
                                "Serveur",
                                "Serveur - Simple Server to deploy virtual machines",
                            ),
                            ("Switch", "Switch - To maintains and connect servers"),
                        ],
                        default="Cisco",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 8, 18, 25, 52, 721965)
            ),
        ),
    ]
