# Generated by Django 4.2 on 2023-06-08 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0015_commutateur_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commutateur",
            name="Type",
        ),
        migrations.RemoveField(
            model_name="commutateur",
            name="maintenanceDate",
        ),
        migrations.AlterField(
            model_name="commutateur",
            name="nom",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 8, 19, 47, 4, 234141)
            ),
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="computerApp.machine",
                    ),
                ),
            ],
        ),
    ]
